Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -17,15 +17,29 @@ jobs:
 
       - name: Deploy to server
         run: |
-          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no $SSH_USER@$SERVER_IP "
-          if [ ! -d $REPO_PATH/.git ]; then
-            git clone https://github.com/panagiotislivanis/coupons.git $REPO_PATH
+          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no $SSH_USER@$SERVER_IP << 'EOF'
+          # Install Docker and Docker Compose if not already installed
+          if ! command -v docker &> /dev/null; then
+            echo "Docker not found, installing..."
+            sudo apt-get update
+            sudo apt-get install -y docker.io
           fi
+          
+          if ! command -v docker-compose &> /dev/null; then
+            echo "Docker Compose not found, installing..."
+            sudo apt-get install -y docker-compose
+          fi
+
+          # Clone repo if not exists
+          if [ ! -d $REPO_PATH/.git ]; then
+            git clone https://github.com/panagiotislivanis/coupons.git $REPO_PATH || { echo 'Cloning failed'; exit 1; }
+          fi
+          
           cd $REPO_PATH/back
           echo 'Current directory: ' $(pwd)
           ls -l
           /snap/bin/docker-compose up --build -d
-          "
+          EOF
         env:
           SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
           SSH_USER: ${{ secrets.SSH_USER }}
